# NumPy (or Numpy) is a Linear Algebra Library for Python
# We ll learn the basics operations of Numpy library

In [1]:
# first install numpy using conda install numpy
# importing numpy
import numpy as np

# Creating Numpy arrays

In [2]:
#We can create an array by directly converting a list
list = [1,2,3,4,5,6]
np.array(list)

array([1, 2, 3, 4, 5, 6])

In [4]:
# using builtin function
np.arange(2,19,4)


array([ 2,  6, 10, 14, 18])

In [9]:
# To generate zeros and ones
np.zeros((3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [8]:
np.ones((4,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [14]:
# Numpy can be used to generate random number arrays
array = np.random.rand(3,3)
array

array([[ 0.21174859,  0.36844819,  0.91282423],
       [ 0.0926978 ,  0.28780148,  0.17813558],
       [ 0.41293526,  0.1677959 ,  0.91930403]])

In [11]:
# unlike random randn return samples from a normal distribution
np.random.randn(3,3)
# similarly randint generate sample random integers

array([[-0.63243761, -1.21197197,  1.72080006],
       [ 0.27220782,  0.17974213,  0.97441852],
       [ 0.02058148, -2.3695355 ,  0.56704901]])

In [17]:
# reshape an array
array.reshape(9,1)
# similarly .max() , .min() can be used to find maximum and minimum values

array([[ 0.21174859],
       [ 0.36844819],
       [ 0.91282423],
       [ 0.0926978 ],
       [ 0.28780148],
       [ 0.17813558],
       [ 0.41293526],
       [ 0.1677959 ],
       [ 0.91930403]])

In [18]:
# To find datatype
#You can also grab the data type of the object in the array:
array.dtype


dtype('float64')

# Array operations using numpy

In [27]:
# Numpy operations are more or less similar to matlab operations
array = np.arange(0,10)

In [28]:
# To find squareroot
np.sqrt(array)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [29]:
# To find cube
array**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [30]:
# To find log
np.log(array)

C:\Users\himanshu\Anaconda2\lib\site-packages\ipykernel\__main__.py:2: RuntimeWarning: divide by zero encountered in log
  from ipykernel import kernelapp as app


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458])